cc_binary(
    name = 'proxy',
    srcs = [
        'proxy.cpp',
    ],
    deps = [
        '//netmt:netmt',
    ]
)

cc_binary(
    name = 'test',
    srcs = [
        'main.cpp',
    ],
    deps = [
        '//netmt:netmt',
    ]
)

